### ISSUE TITLE
Aufruf des YASGUI URL Shorteners wird vom Browser blockiert

### ISSUE THREAD

**Issue by mchlrch** [statistikstadtzuerich/ld.stadt-zuerich.ch#27]
Das Shortening der URL erfolgt zurzeit als Serviceaufruf zu http://yasgui.org/shorten und wird vom Browser abgeblockt.

Die Fehlermeldung in der Browser Console ist wie folgt:
```
VM30:1 Mixed Content:
The page at 'https://ld.stadt-zuerich.ch/sparql/#' was loaded over HTTPS,
but requested an insecure XMLHttpRequest endpoint
'http://yasgui.org/shorten?url=https%3A%2F%2Fld.stadt-zuerich.ch%2Fsparql%2F%23query ...'.
This request has been blocked; the content must be served over HTTPS.
```

YASGUI muss entsprechend mit der HTTPS URL des Shorteners konfiguriert werden: `https://yasgui.org/shorten`

**Comment by l00mi** [comment]
It is set here: https://github.com/zazuko/trifid-plugin-yasgui/blob/master/views/index.html

It might be best to extend this code that it is going for https or http regarding the website. It might work by just specifying `//yasgui.org/shorten` (also see https://stackoverflow.com/a/8951636/496342) else it might be necessary actively check for the protocol and set the variable.

**Comment by mchlrch** [comment]
Fixed by using the scheme-less URL: `//yasgui.org/shorten`. Thanks @l00mi !
Tested successfully with Firefox and Chrome.
