### ISSUE TITLE
Complete views

### ISSUE THREAD

**Issue by mchlrch** [StatistikStadtZuerich/ld.stadt-zuerich.ch#28]
After merging https://github.com/zazuko/trifid/pull/41 customizing the views requires to copy all views to the project folder, which uses Trifid as dependency.

Todo: copy index.html, error.html and home.html.

**Comment by bergos** [comment]
There was already a local version of `home.html`. I added `index.html` and `error.html` with f3a94845bd16c317534647e47c60b626e7058785

Should I trigger a build?
